language: ruby
rvm:
  - 1.9.3
  - 2.0.0

addons:
  postgresql: 9.2

before_script:
  - psql -c 'create database dummy_test;' -U postgres

script:
  - cd spec/dummy/
  - bundle exec rake db:test:prepare
  - cd ../..
  - bundle exec rspec
